### ISSUE TITLE
[BUG] Cannot open Delta Lake checkpoint parquet file

### ISSUE THREAD

**Issue by felipepessoto** [mukunku/ParquetViewer#95]
**Parquet Viewer Version**
2.8.0

**Where was the parquet file created?**
Apache Spark

**Sample File**
https://github.com/delta-io/delta/blob/8639c411890a5c77386f04e2282fcf4caa401eff/spark/src/test/resources/delta/history/delta-0.2.0/_delta_log/00000000000000000003.checkpoint.parquet

**Describe the bug**
```
---------------------------
There is no row at position 1.
---------------------------
Something went wrong (CTRL+C to copy):

System.IndexOutOfRangeException: There is no row at position 1.

   at System.Data.RBTree`1.GetNodeByIndex(Int32 userIndex)

   at System.Data.DataRowCollection.get_Item(Int32 index)

   at ParquetViewer.Engine.ParquetEngine.GetRow(DataTable dataTable, Int32 rowIndex)

   at ParquetViewer.Engine.ParquetEngine.ReadStructField(DataTable dataTable, ParquetRowGroupReader groupReader, Int32 rowBeginIndex, ParquetSchemaElement field, Int64 skipRecords, Int64 readRecords, Boolean isFirstColumn, CancellationToken cancellationToken, IProgress`1 progress)

   at ParquetViewer.Engine.ParquetEngine.ProcessRowGroup(DataTable dataTable, ParquetRowGroupReader groupReader, Int64 skipRecords, Int64 readRecords, CancellationToken cancellationToken, IProgress`1 progress)

   at ParquetViewer.Engine.ParquetEngine.PopulateDataTable(DataTable dataTable, ParquetReader parquetReader, Int64 offset, Int64 recordCount, CancellationToken cancellationToken, IProgress`1 progress)

   at ParquetViewer.Engine.ParquetEngine.ReadRowsAsync(List`1 selectedFields, Int32 offset, Int32 recordCount, CancellationToken cancellationToken, IProgress`1 progress)

   at ParquetViewer.MainForm.<>c__DisplayClass35_0.<<LoadFileToGridview>b__1>d.MoveNext()

--- End of stack trace from previous location ---

   at ParquetViewer.MainForm.LoadFileToGridview()

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

   at InvokeStub_SendOrPostCallback.Invoke(Object, Object, IntPtr*)

   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
---------------------------
OK   
---------------------------

```

**Screenshots**
![image](https://github.com/mukunku/ParquetViewer/assets/1336227/8686eb8a-b4f6-494c-a8d9-7497b2857746)

**Comment by mukunku** [comment]
Thanks for opening this ticket and providing a sample file. This has been fixed now in: [v2.8.1.1](https://github.com/mukunku/ParquetViewer/releases/tag/v2.8.1.1)

Unfortunately three fields in your sample file are still unsupported, though.

**Comment by felipepessoto** [comment]
Thanks. Just curious, do you know why these 3 fields are not supported?

**Comment by mukunku** [comment]
Haven't checked but most likely they are nested complex types: list within struct, struct within struct, etc. We currently don't support those.

**Comment by felipepessoto** [comment]
Yes, it does.

Thanks
